FreelancerJobs/Controllers/Owner/HomeOwnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FreelancerJob.Logic.Repositories;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace FreelancerJobs.Controllers.Owner
{
    public class HomeOwnerController : Controller
    {
        public IConfiguration Configuration { get; set; }
        private readonly SignInManager<IdentityUser> _signInManager;
        public HomeOwnerController(IConfiguration configuration, SignInManager<IdentityUser> signInManager)
        {
            Configuration = configuration;
            _signInManager = signInManager;
        }
        public IActionResult Index()
        {
            var connectionString = Configuration.GetConnectionString("FreelancerJobsContextConnection");
            var templateRepo = new ProjectTemplateRepository(connectionString);
            var allTemplates = templateRepo.GetAllTemplates();
            ViewData["AllTemplates"] = allTemplates;
            return View();
        }

        public IActionResult GetAllProjects([DataSourceRequest] DataSourceRequest dataSource)
        {
            try
            {
                var onlineuser = HttpContext.User.Identity.Name;
                var idUser = _signInManager.UserManager.Users.Where(x => x.UserName == onlineuser).FirstOrDefault();
                var connectionString = Configuration.GetConnectionString("FreelancerJobsContextConnection");
                var projectRps=new ProjectRepository(connectionString);
                var allprojectsData = projectRps.GetAllProjectsOfUser(new Guid(idUser.Id));
                return  Json(allprojectsData.ToDataSourceResult(dataSource));
            }
            catch (Exception e)
            {
                return null;
            }
        }
    }
}

FreelancerJobs/Controllers/Owner/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace FreelancerJobs.Controllers.Owner
{
    public class ProjectController : Controller
    {
        public IActionResult Index(string templateId,string templateName)
        {
            ViewData["TemplateId"] = templateId;
            ViewData["TemplateName"] = templateName;

            return View();
        }
        public IActionResult PriceAndDeadLine(int templateId, string projectName,string projectDescription)
        {
            ViewData["TemplateId"] = templateId;
            ViewData["ProjectName"] = projectName;
            ViewData["ProjectDescription"] = projectDescription;
            return View();
        }
    }
}

FreelancerJobs/Views/HomeOwner/Index.cshtml
@using Kendo.Mvc.UI
@using FreelancerJob.Logic.ViewModels
<div>

    <div>
        <label class="ab-b-l">your Projects</label>
        @(Html.Kendo().Grid<ProjectViewModel>()
        .Name("AllProjects")
        .Columns(columns =>
        {
            columns.Bound(p => p.Id).Visible(false);
            columns.Bound(p => p.Name).Title("Project Name");
            columns.Bound(p => p.PriceRange).Title("Price Range");
            columns.Bound(p => p.StringDate).Title("Selected DeadLine");


        })
        .Scrollable()
        .Pageable()
        .Filterable()
        .DataSource(datasource=>
            datasource.Ajax()
                .ServerOperation(false)
                .Model(model =>
                {
                    model.Id((p=>p.Id));
                    model.Field(p => p.Name);
                    model.Field(p => p.PriceRange);
                    model.Field(p => p.StringDate);
                }
                    )
                .Read(read=>read.Action("GetAllProjects", "HomeOwner"))

        ))



    </div>
    <div>
        <div>
            You Can Request A Project Using This Templates:
            With Templates You can Specify your projects Accuratly

        </div>

        <div class="w3-sidebar w3-bar-block w3-card" style="width:100%">
            <h5 class="w3-bar-item">Templates</h5>

            <div style="width:130px">
                @{

                    var allTemplates = (List<ProjectTemplateViewModel>)ViewData["AllTemplates"];
                    foreach (var item in allTemplates)
                    {


                        <button class="w3-bar-item w3-button tablink" onclick="openLink(event, '@item.Id')">@item.Name</button>

                    }
                }
            </div>
        <div style="margin-left:140px">
            <div class="w3-padding">Use Create Button To Create ProjectBased On Template</div>
            @{

                //var allTemplates = (List<ProjectTemplateViewModel>)ViewData["AllTemplates"];
                foreach (var item in allTemplates)
                {



                    <div id="@item.Id" class="w3-container city w3-animate-opacity" style="display:none">
                        <h2>@item.Name</h2>
                        <p>@item.Description</p>
                        <button class="k-i-create-table" onclick="onclickBtTemplate(event,'@item.Id','@item.Name','@Url.ActionLink("Index", "Project")')">Create</button>
                    </div>
                }
            }
        </div>
        </div>
        </div>
    </div>


<script>
    function openLink(evt, animName) {
        var i, x, tablinks;
        x = document.getElementsByClassName("city");
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablink");
        for (i = 0; i < x.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" w3-red", "");
        }
        document.getElementById(animName).style.display = "block";
        evt.currentTarget.className += " w3-red";
    };
</script>
<script src="~/js/Project.js"></script>